
export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'
export const SESSION_ENDED = 'SESSION_ENDED'
export const NO_INTERNET = 'NO_INTERNET'


export const FETCHING_KEY_DATA = 'FETCHING_DATA'
export const FETCHING_KEY_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_KEY_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT'
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_FAILED = 'LOGIN_FAILED'


export const REGISTER_ATTEMPT = 'REGISTER_ATTEMPT'
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL'
export const REGISTRATION_FAILED = 'REGISTER_FAILED'

export const PASSWORD_SENT_REQUEST = 'PASSWORD_SENT_REQUEST'
export const SENT_SUCCESSFUL = 'SENT_SUCCESSFUL'
export const SENT_FAILED = 'SENT_FAILED'

